import Head from "next/head"
import Header from "../src/components/Header"

const Home = () => {
  return (
    <div>
      <Head>
        <title>Project Blog </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  )
}

export default Home
